version: 2

seeds: 
    - name: employees
      description: Lookup table for Customer-Employee mapping
      columns: 
        - name: employee_id
          description: Primary key of employees
          tests:
            - unique
            - not_null